In [1]:
import os
import sys
import numpy as np
import pandas as pd

from sklearn.utils import shuffle
sys.path.append( os.getcwd()+'/modules' )
import aux_functions

In [2]:
#Loading datasets
os.chdir( "/home/toful/Documents/DataSets/cresci-2017.csv/datasets_full.csv/" )

real = pd.read_csv( 'genuine_accounts.csv/genuine_accounts.csv/users.csv' )
real = real.fillna( '' )
real['knownbot'] = 0

fakeFollowers = pd.read_csv('fake_followers.csv/fake_followers.csv/users.csv', na_filter=False)
fakeFollowers = fakeFollowers.fillna( '' )
fakeFollowers['knownbot'] = 1

df = pd.concat( [ real, fakeFollowers ], sort=False )
df = shuffle( df )
print df.head()
print df.info()


             id              name     screen_name  statuses_count  \
209   108581391           Matorah         Matorah              10   
3344  888376710       zaynmalik1D  untouchablarry           42079   
2898    8548002     Chase Raymond         ochaser            3396   
2056  616210933    Malvina Riddle     riddleualuz              54   
3027  619369704  Kathe Strickland     kathestrick              25   

      followers_count  friends_count  favourites_count  listed_count  \
209                 2            620                 0             0   
3344             6692           4497             10431            75   
2898              104            386                73             3   
2056               16            637                 0             0   
3027               25            250                 0             0   

                       url lang  ...  \
209   http://t.co/4F4zeDEd   en  ...   
3344                         en  ...   
2898                         en 

In [3]:
#Building the working dataset
score = pd.DataFrame()
score['id'] = df['id']

score['lang-en'] = df.apply( lambda row: aux_functions.language (row), axis=1 )
score['profile_pic'] = df.apply( lambda row: aux_functions.profile_image (row), axis=1 ) #check this feature
score['def_profile_pic'] = df.apply( lambda row: aux_functions.def_profile_image (row), axis=1 )
score['has_screen_name'] = df.apply( lambda row: aux_functions.screen_name (row), axis=1 )
score['30followers'] = df.apply( lambda row: aux_functions.min_followers (row, 30), axis=1 )
score['1000friends'] = df.apply( lambda row: aux_functions.min_friends (row, 1000), axis=1 )
score['twice_num_followers'] = df.apply( lambda row: aux_functions.ratio_followers (row), axis=1 )
score['fifty_FriendsFollowersRatio'] = df.apply( lambda row: aux_functions.ratio_followers2 (row, 50), axis=1 )
score['hundred_FriendsFollowersRatio'] = df.apply( lambda row: aux_functions.ratio_followers2 (row, 100), axis=1 )
score['geoloc'] = df.apply( lambda row: aux_functions.location (row), axis=1 )
score['banner_link'] = df.apply( lambda row: aux_functions.profile_banner (row), axis=1 )
score['50tweets'] = df.apply( lambda row: aux_functions.tweets_written (row, 50), axis=1 )
score['20statuses'] = df.apply( lambda row: aux_functions.min_statuses (row, 20), axis=1 )
score['NeverTweeted'] = df.apply( lambda row: aux_functions.never_tweeted (row ), axis=1 )
score['has_description'] = df.apply( lambda row: aux_functions.description (row), axis=1 )
score['knownbot'] = df.apply( lambda row: aux_functions.knownbot (row), axis=1 )

print score.shape
print score.describe()

score

(6825, 17)
                 id      lang-en  profile_pic  def_profile_pic  \
count  6.825000e+03  6825.000000       6825.0      6825.000000   
mean   8.499737e+08     0.898022          0.0         0.002784   
std    7.662248e+08     0.302642          0.0         0.052693   
min    6.780330e+05     0.000000          0.0         0.000000   
25%    2.597067e+08     1.000000          0.0         0.000000   
50%    6.168972e+08     1.000000          0.0         0.000000   
75%    1.174963e+09     1.000000          0.0         0.000000   
max    3.164942e+09     1.000000          0.0         1.000000   

       has_screen_name  30followers  1000friends  twice_num_followers  \
count      6825.000000  6825.000000  6825.000000          6825.000000   
mean          0.000147     0.492601     0.076337             0.588425   
std           0.012105     0.499982     0.265556             0.492155   
min           0.000000     0.000000     0.000000             0.000000   
25%           0.000000     0.

id  lang-en  profile_pic  def_profile_pic  has_screen_name  \
209    108581391        1            0                0                0   
3344   888376710        1            0                0                0   
2898     8548002        1            0                0                0   
2056   616210933        1            0                0                0   
3027   619369704        1            0                0                0   
2488  1132139449        1            0                0                0   
217    112131340        1            0                0                0   
663    357756459        0            0                0                0   
2706   617228381        1            0                0                0   
1906  1176224780        1            0                0                0   
1599  1175006178        1            0                0                0   
203    106595346        0            0                0                0   
1868  1176157068        1            0                0                0   
34      31776715        1            0                0                0   
957   1127238390        1            0                0                0   
2337   616299435        1            0                0                0   
2314   616294011        1            0                0                0   
1005  1127645011        1            0                0                0   
1001  1127587958        1            0                0                0   
3035    54252876        1            0                0                0   
1735  1175831797        1            0                0                0   
349    169497745        0            0                0                0   
2639    80976396        1            0                0                0   
863    887026338        1            0                0                0   
1045  1127963340        1            0                0                0   
994   1127536843        1            0                0                0   
922   2596494170        1            0                0                0   
722    414022154        0            0                0                0   
830   1232534634        1            0                0                0   
3243  1375713390        1            0                0                0   
...          ...      ...          ...              ...              ...   
2500  1029836556        1            0                0                0   
1693    54125633        1            0                0                0   
1517  2484688494        1            0                0                0   
1516  1174848200        1            0                0                0   
3375   412982588        1            0                0                0   
2170   616223692        1            0                0                0   
1198   374686451        0            0                0                0   
1218  1130409716        1            0                0                0   
116     69412978        1            0                0                0   
1011   538794415        1            0                0                0   
1699  1175754096        1            0                0                0   
2969   618438937        1            0                0                0   
1999  1176388189        1            0                0                0   
1702    29745877        1            0                0                0   
1249    46331521        1            0                0                0   
2742  2571493866        1            0                1                0   
426    428641140        1            0                0                0   
1853  1176120306        1            0                0                0   
2546   199562994        1            0                0                0   
708    397930399        1            0                0                0   
116    622956477        1            0                0       

# Data Analisis

In [4]:
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics as mt

In [5]:
#Preparing the X and Y values for the machine learning analisis
if 'knownbot' in score:
    y = score['knownbot'].values # get the labels we want
    del score['knownbot'] # get rid of the class label
    X = score.values # use everything else to predict

In [6]:
num_cv_iterations = 3
num_instances = len(y)
cv_object = ShuffleSplit( n_splits=num_cv_iterations, test_size = 0.2 )

# first we create a reusable logisitic regression and random forest objects
lr_clf = LogisticRegression( penalty='l2', C=1.0, class_weight=None ) # get object
rf_clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

iter_num=0
# the indices are the rows used for training and testing in each iteration
for train_indices, test_indices in cv_object.split( X, y ):
    X_train = X[train_indices]
    y_train = y[train_indices]
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    # train the reusable logisitc regression model on the training data
    #lr_clf.fit( X_train, y_train ) # train object
    #y_pred = lr_clf.predict( X_test ) # get test set precitions
   
    rf_clf.fit( X_train, y_train ) # train object
    y_pred = rf_clf.predict( X_test ) # get test set precitions
    acc = mt.accuracy_score( y_test, y_pred )
    conf = mt.confusion_matrix( y_test, y_pred )
    # now let's get the accuracy and confusion matrix for this iterations of training/testing
    print "\n====Iteration",iter_num," ===="
    print "RANDOM FOREST"
    print "accuracy: ", acc
    print "confusion matrix\n", conf
    tp = float( conf[1][1] )
    fp = float( conf[0][1] )
    fn = float( conf[1][0] )
    precission = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1 = 2*precission*recall/(precission+recall)
    print "F1: ", f1, "\tPrecission: ", precission, "\tRecall: ", recall
    iter_num+=1
    


====Iteration 0  ====
RANDOM FOREST
accuracy:  0.9582417582417583
confusion matrix
[[708  20]
 [ 37 600]]
F1:  0.954653937947 	Precission:  0.967741935484 	Recall:  0.94191522763

====Iteration 1  ====
RANDOM FOREST
accuracy:  0.9575091575091575
confusion matrix
[[651  24]
 [ 34 656]]
F1:  0.957664233577 	Precission:  0.964705882353 	Recall:  0.950724637681

====Iteration 2  ====
RANDOM FOREST
accuracy:  0.9611721611721612
confusion matrix
[[684  24]
 [ 29 628]]
F1:  0.959511077158 	Precission:  0.963190184049 	Recall:  0.955859969559


In [7]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

1.13.1


In [12]:
#Setting up the model layers
#https://www.tensorflow.org/api_docs/python/tf/keras/layers
model = keras.Sequential( [ keras.layers.Dense( 32, input_shape=( len(X[0]), ) ),
                            keras.layers.Dense( 40, activation = tf.nn.relu ),
                            keras.layers.Dense( 2, activation = tf.nn.softmax ) ] )
#model = keras.Sequential( )
#model.add( keras.layers.Dense( 32, input_shape = ( len(X[0]), ) ) )
#model.add( keras.layers.Dense( 2 ) )


#Compiling the model
  #Loss function — This measures how accurate the model is during training. We want to minimize 
                   #this function to "steer" the model in the right direction.
  #Optimizer — This is how the model is updated based on the data it sees and its loss function.
  #Metrics —  Used to monitor the training and testing steps. The following example uses accuracy,
              #the fraction of the images that are correctly classified.
model.compile( optimizer='adam', 
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'] )

num_cv_iterations = 3
cv_object = ShuffleSplit( n_splits=num_cv_iterations, test_size = 0.2 )
iter_num = 1

for train_indices, test_indices in cv_object.split( X, y ):
    X_train = X[train_indices]
    y_train = y[train_indices]
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    print "\n\n====Iteration",iter_num," ===="
    
    model.fit( X_train, y_train, epochs=5)
    test_loss, test_acc = model.evaluate( X_test, y_test )
    y_pred = model.predict( X_test )
    aux=[]
    for i in range( len( y_pred ) ):
        aux += [ np.argmax( y_pred[i] ) ]
    conf = mt.confusion_matrix( y_test, aux )
    
    print '\nMODEL RESULTS\n\tTest accuracy: ', test_acc, 'Test loss: ', test_loss
    print "PREDICTION RESULTS"
    print "confusion matrix\n", conf
    tp = float( conf[1][1] )
    fp = float( conf[0][1] )
    fn = float( conf[1][0] )
    try:  
        precission = tp / (tp + fp)
        recall = tp / (tp + fn)
        f1 = 2*precission*recall/(precission+recall)
    except ArithmeticError:  
        print ("Arithmetic exception raised." )
    else: 
        print "\tF1: ", f1, "\tPrecission: ", precission, "\tRecall: ", recall
    iter_num+=1

#print y_pred



====Iteration 1  ====
Epoch 1/5
5460/5460 [==============================] - 1s 96us/sample - loss: 8.2450 - acc: 0.4885
Epoch 2/5
5460/5460 [==============================] - 0s 63us/sample - loss: 8.2450 - acc: 0.4885
Epoch 3/5
5460/5460 [==============================] - 0s 61us/sample - loss: 8.2450 - acc: 0.4885
Epoch 4/5
5460/5460 [==============================] - 0s 56us/sample - loss: 8.2450 - acc: 0.4885
Epoch 5/5
1365/1365 [==============================] - 0s 83us/sample - loss: 8.0413 - acc: 0.5011

MODEL RESULTS
	Test accuracy:  0.50109893 Test loss:  8.041335632338193
PREDICTION RESULTS
confusion matrix
[[  0 681]
 [  0 684]]
	F1:  0.667642752562 	Precission:  0.501098901099 	Recall:  1.0


====Iteration 2  ====
Epoch 1/5
5460/5460 [==============================] - 0s 61us/sample - loss: 8.2214 - acc: 0.4899
Epoch 2/5
5460/5460 [==============================] - 0s 52us/sample - loss: 8.2214 - acc: 0.4899
Epoch 3/5
5460/5460 [==============================] - 0s 48us/